"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { authApi } from "@/lib/api/auth";
import { ApiError } from "@/lib/api/errors";
import { ForgotPasswordForm } from "./ForgotPasswordForm";

export function ResetPasswordView() { const search = useSearchParams(); const token = search.get("token"); const [valid, setValid] = useState<boolean | null>(token ? null : false); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false); useEffect(() => { if (!token) return; void authApi.validateResetToken(token).then(() => setValid(true)).catch((failure) => { setValid(false); setError(failure instanceof ApiError ? failure.message : "This reset link is invalid."); }); }, [token]); if (!token) return <ForgotPasswordForm />; if (valid === null) return <div className="card">Checking reset link…</div>; if (!valid) return <div className="card"><div className="error-box" role="alert">{error ?? "This reset link is invalid or expired."}</div><Link href="/reset-password" className="button mt-5">Request a new link</Link></div>; async function submit(event: FormEvent) { event.preventDefault(); if (password !== confirm) { setError("Passwords must match."); return; } if (!token) return; setPending(true); setError(null); try { await authApi.resetPassword(token, password); setMessage("Password reset successfully. You can sign in with the new password."); } catch (failure) { setError(failure instanceof ApiError ? failure.message : "Password reset failed."); } finally { setPending(false); } } return <form className="card grid gap-5" onSubmit={submit}><div className="field"><label htmlFor="new-password">New password</label><input id="new-password" type="password" autoComplete="new-password" value={password} onChange={(e) => setPassword(e.target.value)} required /></div><div className="field"><label htmlFor="confirm-password">Confirm new password</label><input id="confirm-password" type="password" autoComplete="new-password" value={confirm} onChange={(e) => setConfirm(e.target.value)} required /></div>{error && <div className="error-box" role="alert">{error}</div>}{message && <div className="success-box" role="status">{message}</div>}<button className="button" disabled={pending}>{pending ? "Resetting…" : "Reset password"}</button><Link href="/login" className="text-center text-sm font-bold text-teal-700">Back to sign in</Link></form>; }
