"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/auth/AuthProvider";
import { authApi } from "@/lib/api/auth";
import { ApiError } from "@/lib/api/errors";
import { triggerAuthExpired } from "@/lib/api/http";

export function PasswordChangeForm() { const { status } = useAuth(); const router = useRouter(); const [form, setForm] = useState({ currentPassword: "", newPassword: "", confirmNewPassword: "" }); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [pending, setPending] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); if (form.newPassword !== form.confirmNewPassword) { setError("New passwords must match."); return; } if (status !== "authenticated") return; setPending(true); setError(null); setMessage(null); try { await authApi.changePassword(form); triggerAuthExpired(); router.push("/login"); } catch (failure) { setError(failure instanceof ApiError ? failure.message : "Password could not be changed."); } finally { setPending(false); } } return <form className="card grid gap-4" onSubmit={submit}><h2 className="text-xl font-black">Change password</h2>{(["currentPassword", "newPassword", "confirmNewPassword"] as const).map((key) => <div className="field" key={key}><label htmlFor={key}>{key === "currentPassword" ? "Current password" : key === "newPassword" ? "New password" : "Confirm new password"}</label><input id={key} type="password" autoComplete={key === "currentPassword" ? "current-password" : "new-password"} value={form[key]} onChange={(e) => setForm((current) => ({ ...current, [key]: e.target.value }))} required /></div>)}{error && <div className="error-box" role="alert">{error}</div>}{message && <div className="success-box" role="status">{message}</div>}<button className="button" disabled={pending}>{pending ? "Saving…" : "Change password"}</button></form>; }
