"use client";

import { FormEvent, useEffect, useState } from "react";
import { useAuth } from "@/components/auth/AuthProvider";
import { usersApi } from "@/lib/api/users";
import { ApiError } from "@/lib/api/errors";
import type { UserProfile } from "@/lib/api/contracts";
import { SectionHeading } from "@/components/layout/ProtectedLayout";
import { PasswordChangeForm } from "./PasswordChangeForm";

export function ProfileView() { const { status, setProfile } = useAuth(); const [profile, setLocalProfile] = useState<UserProfile | null>(null); const [email, setEmail] = useState(""); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [pending, setPending] = useState(false); useEffect(() => { if (status !== "authenticated") return; void usersApi.me().then((value) => { setLocalProfile(value); setProfile(value); setEmail(value.email ?? ""); }).catch((failure) => setError(failure instanceof ApiError ? failure.message : "Profile could not be loaded.")); }, [setProfile, status]); async function submit(event: FormEvent) { event.preventDefault(); if (status !== "authenticated") return; setPending(true); setError(null); setMessage(null); try { await usersApi.changeEmail({ newEmail: email.trim() }); setMessage("Email change request submitted. Follow any verification instructions from the server."); } catch (failure) { setError(failure instanceof ApiError ? failure.message : "Email could not be changed."); } finally { setPending(false); } } return <><SectionHeading title="Your profile" />{error && <div className="error-box mb-5" role="alert">{error}</div>}{profile && <div className="grid gap-5 md:grid-cols-2"><div className="card"><h2 className="text-xl font-black">Identity</h2><dl className="mt-4 grid gap-3 text-sm"><div><dt className="font-bold">Username</dt><dd>{profile.username}</dd></div><div><dt className="font-bold">Name</dt><dd>{[profile.firstName, profile.lastName].filter(Boolean).join(" ") || "—"}</dd></div><div><dt className="font-bold">Role</dt><dd>{profile.roleName}</dd></div></dl></div><form className="card grid gap-4" onSubmit={submit}><h2 className="text-xl font-black">Email</h2><div className="field"><label htmlFor="profile-email">Email address</label><input id="profile-email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></div>{message && <div className="success-box" role="status">{message}</div>}<button className="button" disabled={pending}>{pending ? "Saving…" : "Request email change"}</button></form><PasswordChangeForm /></div>}</>; }
